# Generated by Django 5.2.7 on 2025-10-12 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
                ('guests', models.IntegerField(default=1)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completa')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('invoice_generated', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking_number'], name='bookings_bo_booking_03d631_idx'), models.Index(fields=['email'], name='bookings_bo_email_2e2fb9_idx'), models.Index(fields=['check_in', 'check_out'], name='bookings_bo_check_i_3b9851_idx')],
            },
        ),
    ]
